name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: debian:12.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: make build
      - name: run
        run: make run