name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: gcc:14.1.0-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: make build
      - name: run
        run: make run