name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: omst/mingw64:2021.03.00-rev2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: make build
      - name: Upload build product
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: ./dist
